<a href="https://colab.research.google.com/github/Mekto90/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)


### <a name='a1'></a> Podstawy

In [ ]:
import numpy as np
np.__version__



'1.25.2'

1D Array

In [ ]:
x = np.array([1, 3])
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 4.5])
print(x)

[1.3 2.3 4.5]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


(2, 3)

3D Array

In [ ]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]]]
    )
print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]]


In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

### <a name='a2'></a> Typy danych

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.2, 2, 3.3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype = 'float')
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype = 'complex')
A.dtype
A.data
A.__lt__(5)

array([ True,  True,  True])

In [ ]:
A = np.array([1, 2, 3])
A.dtype

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
A = np.array([1, 2.3, 3], dtype = 'int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype
print(A)

[ 24 120 230]


### <a name='a3'></a> Tworzenie tablic

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype = 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5, 5), dtype = 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype = 'int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop = 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop = 100, step = 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop = 10, step = -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start = 0, stop = 1, step = 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2,])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A + B

array([6, 0, 7, 4])

In [ ]:
A - B

array([0, 2, 1, 0])

In [ ]:
A * B

array([ 9, -1, 12,  4])

In [ ]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
A * 2

array([6, 2, 8, 4])

In [ ]:
A + 3 * B

array([12, -2, 13,  8])

In [ ]:
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
X * Y

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

### <a name='a5'></a>  Generowanie liczb pseudolosowych

In [ ]:
import numpy as np
np.random.seed(0)

In [ ]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
np.random.rand()

0.1965823616800535

In [ ]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [ ]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [ ]:
np.random.randint(10)

3

In [ ]:
np.random.randint(low=10, high =101)

56

In [ ]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [ ]:
np.random.choice([4, 2, 1, 3])

3

In [ ]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([1, 0, 5, 2, 9, 7, 4, 6, 8, 3])

NameError: name 'np' is not defined

NameError: name 'data' is not defined

### <a name='a6'></a> Podstawowe funkcje

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9)

3.0

In [ ]:
np.all([2, 3, 1])

True

In [ ]:
np.any([0, 0, 0])

False

In [ ]:
bool(4)

True

In [ ]:
A = np.random.rand(5)
A

array([0.13547406, 0.29828233, 0.56996491, 0.59087276, 0.57432525])

In [ ]:
np.argmax(A)

3

In [ ]:
A[np.argmax(A)]

0.5908727612481732

In [ ]:
A

array([0.13547406, 0.29828233, 0.56996491, 0.59087276, 0.57432525])

In [ ]:
np.argmin(A)

0

In [ ]:
np.argsort(A)

array([0, 1, 2, 4, 3])

In [ ]:
np.max(A)

0.5908727612481732

In [ ]:
np.min(A)

0.13547406422245023

In [ ]:
np.mean(A)

0.4337838621954996

In [ ]:
np.median(A)

0.5699649107012649

In [ ]:
np.std(A)

0.18456623929112265

###  <a name='a7'></a> Indeksowanie, Wycinanie

In [ ]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#A[idx], A[start:stop], A[:stop], A[start:]

In [ ]:
A[2]

2

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:2]

array([0, 1])

In [ ]:
A[[0, 2]]

array([0, 2])

In [ ]:
A[-1]

19

In [ ]:
A[10:15]

array([10, 11, 12, 13, 14])

In [ ]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[0]

array([0, 1, 2, 3, 4])

In [ ]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

### <a name='a8'></a> Iteracja po tablicach

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [ ]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

In [ ]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A < 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])